apiVersion: v1
kind: Pod
metadata:
  name: anycode-sidecar-pod
  labels:
      app: AnyCodeApp
spec:
  shareProcessNamespace: true
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
        name: nginx-c-port
  - name: anycode
    image: danielmeixner/anycode:latest
    ports:
      - containerPort: 8888
        name: anycode-c-port 
---
apiVersion: v1
kind: Service
metadata:
  name: anycode-sidecar-service
spec:
  type: LoadBalancer
  selector:
    app: AnyCodeApp
  ports:
  - protocol: TCP
    port: 80
    name: nginx-svc-port
    targetPort: 80
  - protocol: TCP
    port: 8888
    name: topz-svc-port
    targetPort: 8888